using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Fragments;
using Content.Shared.FixedPoint;
using Content.Shared.Paradise.Mech;
using Content.Shared.Paradise.Mech.Components;
using Content.Shared.Paradise.Mech.Parts.Components;
using Content.Shared.Paradise.Mech.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Paradise.Mech.Ui;

[GenerateTypedNameReferences]
public sealed partial class AltMechMenu : FancyWindow
{
    public event Action<PartSlot>? OnRemovePartButtonPressed;

    public event Action<EntityUid>? OnRemoveEquipmentButtonPressed;

    [Dependency] private IEntityManager _ent = default!;

    private EntityUid _mech;

    public event Action<bool>? OnMaintenancePressed;

    public event Action<bool>? OnBoltButtonPressed;

    public event Action<bool>? OnSealButtonPressed;

    public event Action<bool>? OnDetachTankButtonPressed;

    public AltMechMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SpriteViewDict[MechPartVisualLayers.Core] = MechViewCore;
        SpriteViewDict[MechPartVisualLayers.Head] = MechViewHead;
        SpriteViewDict[MechPartVisualLayers.RightArm] = MechViewRightArm;
        SpriteViewDict[MechPartVisualLayers.LeftArm] = MechViewLeftArm;
        SpriteViewDict[MechPartVisualLayers.Chassis] = MechViewChassis;
        SpriteViewDict[MechPartVisualLayers.Power] = MechViewPower;

        IntegrityBarDict[IntegrityDisplayBarCore] = PartSlot.Core;
        IntegrityBarDict[IntegrityDisplayBarHead] = PartSlot.Head;
        IntegrityBarDict[IntegrityDisplayBarRightArm] = PartSlot.RightArm;
        IntegrityBarDict[IntegrityDisplayBarLeftArm] = PartSlot.LeftArm;
        IntegrityBarDict[IntegrityDisplayBarChassis] = PartSlot.Chassis;
        IntegrityBarDict[IntegrityDisplayBarPower] = PartSlot.Power;

        SpriteTextDict[IntegrityDisplayCore] = PartSlot.Core;
        SpriteTextDict[IntegrityDisplayHead] = PartSlot.Head;
        SpriteTextDict[IntegrityDisplayRightArm] = PartSlot.RightArm;
        SpriteTextDict[IntegrityDisplayLeftArm] = PartSlot.LeftArm;
        SpriteTextDict[IntegrityDisplayChassis] = PartSlot.Chassis;
        SpriteTextDict[IntegrityDisplayPower] = PartSlot.Power;

        ButtonDict[RemoveButtonHead] = PartSlot.Head;
        ButtonDict[RemoveButtonRightArm] = PartSlot.RightArm;
        ButtonDict[RemoveButtonLeftArm] = PartSlot.LeftArm;
        ButtonDict[RemoveButtonChassis] = PartSlot.Chassis;
        ButtonDict[RemoveButtonPower] = PartSlot.Power;

        foreach (var key in ButtonDict.Keys)
        {
            key.TexturePath = "/Textures/_Paradise/Interface/Mech/detach_button.png";
            key.OnPressed += _ => OnRemovePartButtonPressed?.Invoke(ButtonDict[key]);
        }

        Maintenance.OnToggled += OnMaintenanceButtonPressed;
        Maintenance.OnToggled += (_) => OnMaintenancePressed?.Invoke(Maintenance.Pressed);
        Maintenance.OnToggled += (_) => UpdateEquipmentView();

        Seal.OnToggled += (_) => OnSealButtonPressed?.Invoke(Seal.Pressed);

        DetachTank.OnPressed += (_) => OnDetachTankButtonPressed?.Invoke(true);

        Bolt.OnPressed += (_) => OnBoltButtonPressed?.Invoke(Bolt.Pressed);
    }

    public readonly Dictionary<MechPartVisualLayers, SpriteView?> SpriteViewDict = new Dictionary<MechPartVisualLayers, SpriteView?>()
    {
        [MechPartVisualLayers.Core] = null,
        [MechPartVisualLayers.Head] = null,
        [MechPartVisualLayers.RightArm] = null,
        [MechPartVisualLayers.LeftArm] = null,
        [MechPartVisualLayers.Chassis] = null,
        [MechPartVisualLayers.Power] = null
    };

    public readonly Dictionary<ProgressBar, PartSlot> IntegrityBarDict = new Dictionary<ProgressBar, PartSlot>();

    public readonly Dictionary<Label, PartSlot> SpriteTextDict = new Dictionary<Label, PartSlot>();

    public Dictionary<TextureButton, PartSlot> ButtonDict = new Dictionary<TextureButton, PartSlot>();

    public void OnMaintenanceButtonPressed(BaseButton.ButtonEventArgs args)
    {
        if (!_ent.TryGetComponent<AltMechComponent>(_mech, out var mechComp))
            return;

        mechComp.MaintenanceMode = args.Button.Pressed;

        foreach (var key in ButtonDict.Keys)
        {
            key.Visible = args.Button.Pressed && mechComp.ContainerDict[ButtonDict[key]].ContainedEntity != null;
        }
    }

    public void SetMaintenance(bool toggled)
    {
        Maintenance.Pressed = toggled;

        foreach (var key in ButtonDict.Keys)
        {
            key.Visible = Maintenance.Pressed;
        }
    }

    public void SetSeal(bool toggled)
    {
        Seal.Pressed = toggled;
    }

    public void SetBolt(bool toggled)
    {
        Bolt.Pressed = toggled;
    }

    public void SetEntity(EntityUid? uid, MechPartVisualLayers part)
    {
        if (!SpriteViewDict.ContainsKey(part))
            return;

        var view = SpriteViewDict[part];

        if (view != null)
            view.SetEntity(uid);

        if (uid == null)
            return;

        if (_ent.TryGetComponent<AltMechComponent>(uid, out var mechComp))
            _mech = (EntityUid)uid;
    }

    public void SetupMechTankData()
    {
        TankPressure.Text = Loc.GetString("mech-tank-pressure", ("amount", FixedPoint2.Zero));
        TankPressure.FontColorOverride = Color.DarkGreen;
        TankGasTemperature.Text = Loc.GetString("mech-tank-temperature", ("amount", FixedPoint2.Zero));
        TankGasTemperature.FontColorOverride = Color.DarkGreen;
    }

    public void UpdateMechTankData(AltMechBoundUiState state)
    {
        TankPressure.Text = Loc.GetString("mech-tank-pressure", ("amount", state.TankPressure));
        TankPressure.FontColorOverride = Color.DarkGreen;
        TankGasTemperature.Text = Loc.GetString("mech-tank-temperature", ("amount", state.TankTemperature));
        TankGasTemperature.FontColorOverride = Color.DarkGreen;
    }

    public void UpdateMechStats()
    {
        if (!_ent.TryGetComponent<AltMechComponent>(_mech, out var mechComp))
            return;

        //var localPartDict = new Dictionary<string, EntityUid?>();

        //foreach (var pair in state.Parts)
        //{
        //    _ent.TryGetEntity(pair.Value, out var entity);
        //    localPartDict.Add(pair.Key, entity);
        //}

        foreach (var key in ButtonDict.Keys)
        {
            key.Visible = mechComp.MaintenanceMode && mechComp.ContainerDict[ButtonDict[key]].ContainedEntity != null;
        }

        var integrityPercent = mechComp.Integrity / mechComp.MaxIntegrity;
        IntegrityDisplayBarCore.Value = integrityPercent.Float();
        IntegrityDisplayCore.Text = Loc.GetString("mech-integrity-display", ("amount", (integrityPercent * 100).Int()));

        foreach (var bar in IntegrityBarDict.Keys)
        {
            if (IntegrityBarDict[bar] == PartSlot.Core)
                continue;

            FixedPoint2 partintegrityPercent;

            if (mechComp.ContainerDict[IntegrityBarDict[bar]].ContainedEntity == null || !_ent.TryGetComponent<MechPartComponent>(mechComp.ContainerDict[IntegrityBarDict[bar]].ContainedEntity, out var partComp))
            {
                partintegrityPercent = 0;
                bar.Value = partintegrityPercent.Float();
                continue;
            }

            partintegrityPercent = partComp.Integrity / partComp.MaxIntegrity;
            bar.Value = partintegrityPercent.Float();
        }

        foreach (var text in SpriteTextDict.Keys)
        {
            if (SpriteTextDict[text] == PartSlot.Core)
                continue;

            if (mechComp.ContainerDict[SpriteTextDict[text]].ContainedEntity == null || !_ent.TryGetComponent<MechPartComponent>(mechComp.ContainerDict[SpriteTextDict[text]].ContainedEntity, out var partComp))
            {
                text.Text = Loc.GetString("mech-integrity-display", ("amount", 0));
                continue;
            }

            var partintegrityPercent = partComp.Integrity / partComp.MaxIntegrity;
            text.Text = Loc.GetString("mech-integrity-display", ("amount", (partintegrityPercent * 100).Int()));
        }

        if (mechComp.MaxEnergy != 0f)
        {
            var energyPercent = mechComp.Energy / mechComp.MaxEnergy;
            EnergyDisplayBar.Value = energyPercent.Float();
            EnergyDisplay.Text = Loc.GetString("mech-energy-display", ("amount", (energyPercent * 100).Int()));
        }
        else
        {
            EnergyDisplayBar.Value = 0f;
            EnergyDisplay.Text = Loc.GetString("mech-energy-missing");
        }

        var entMan = IoCManager.Resolve<IEntityManager>();
        var mechSys = entMan.System<SharedAltMechSystem>();

        foreach (var part in mechComp.ContainerDict)
        {
            SetEntity(part.Value.ContainedEntity, mechSys.PartsVisuals[part.Key]);
        }

        SlotDisplay.Text = Loc.GetString("mech-equipment-slot-display", ("amount", mechComp.MaxEquipmentAmount - mechComp.CurrentEquipmentAmount));
    }

    public void UpdateEquipmentView()
    {
        if (!_ent.TryGetComponent<AltMechComponent>(_mech, out var mechComp))
            return;

        EquipmentControlContainer.Children.Clear();

        if (!_ent.TryGetComponent<MechPartComponent>(_mech, out var partCore))
            return;

        foreach (var ent in mechComp.EquipmentContainer.ContainedEntities)
        {
            if (!_ent.TryGetComponent<MetaDataComponent>(ent, out var metaData))
                continue;

            var uicomp = _ent.GetComponentOrNull<UIFragmentComponent>(ent);
            var ui = uicomp?.Ui?.GetUIFragmentRoot();

            var control = new AltMechEquipmentControl(ent, metaData.EntityName, ui, mechComp.MaintenanceMode);

            control.OnRemoveButtonPressed += () => OnRemoveEquipmentButtonPressed?.Invoke(ent);

            EquipmentControlContainer.AddChild(control);
        }
    }
}

