using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Paradise.Mech.Ui;

[GenerateTypedNameReferences]
public sealed partial class AltMechEquipmentControl : Control
{
    public event Action? OnRemoveButtonPressed;

    public AltMechEquipmentControl(EntityUid entity, string itemName, Control? fragment, bool buttonVisible = true)
    {
        RobustXamlLoader.Load(this);
        EquipmentName.SetMessage(itemName);
        EquipmentView.SetEntity(entity);
        RemoveButton.TexturePath = "/Textures/Interface/Nano/cross.svg.png";
        RemoveButton.Visible = buttonVisible;

        if (fragment != null)
        {
            Separator.Visible = true;
            CustomControlContainer.AddChild(fragment);
        }

        RemoveButton.OnPressed += _ => OnRemoveButtonPressed?.Invoke();
    }
}
