using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaNavigationButton : ContainerButton
{

    private bool _isCurrent;
    private bool _isActive = true;

    private Thickness _borderThickness = new(0, 0, 0, 2);
    private Thickness _currentTabBorderThickness = new(2, 0, 2, 0);

    private readonly StyleBoxFlat _styleBox = new()
    {
        BackgroundColor = Color.FromHex("#202023"),
        BorderColor = Color.FromHex("#5a5a5a"),
        BorderThickness = new Thickness(0, 0, 0, 2)
    };

    public string InactiveBgColor { get; set; } = "#202023";
    public string ActiveBgColor { get; set; } = "#25252a";
    public string InactiveFgColor { get; set; } = "#5a5a5a";
    public string ActiveFgColor { get; set; } = "#FFFFFF";

    public SpriteSpecifier? IconTexture
    {
        set
        {
            Icon.Visible = value != null;
            Label.Visible = value == null;

            if (value is not null)
                Icon.SetFromSpriteSpecifier(value);
        }
    }

    public Vector2 IconScale
    {
        get => Icon.DisplayRect.TextureScale;
        set => Icon.DisplayRect.TextureScale = value;
    }

    public string? LabelText
    {
        get => Label.Text;
        set => Label.Text = value;
    }

    public PdaNavigationButton()
    {
        RobustXamlLoader.Load(this);
    }
}
