using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Chat.UI._Paradise;

[GenerateTypedNameReferences]
public sealed partial class TelepathicChatComposeWindow : FancyWindow
{
    public event Action<string>? OnTextEntered;
    public event Action? CancelPressed;

    public TelepathicChatComposeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CancelButton.OnPressed += _ => CancelPressed?.Invoke();
        TextLine.OnTextEntered += EnteredText;

    }

    public void EnteredText(LineEdit.LineEditEventArgs args)
    {
        var submittedText = args.Text;
        OnTextEntered?.Invoke(submittedText);
    }
}