using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Chat.UI._Paradise;

[GenerateTypedNameReferences]
public sealed partial class TelepathicChatMenu : FancyWindow
{
    public event Action? SelectPressed;
    public event Action? CancelPressed;
    public event Action<NetEntity>? OnTargetSelected;

    public TelepathicChatMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SelectButton.OnPressed += _ => SelectPressed?.Invoke();
        CancelButton.OnPressed += _ => CancelPressed?.Invoke();
        TargetsList.OnItemSelected += OnItemSelected;
    }

    // TODO ALL of this does not work
    public void OnItemSelected(ItemList.ItemListSelectedEventArgs obj)
    {
        var item = TargetsList[obj.ItemIndex].Metadata;

        if (item is NetEntity netEntity)
        {
            OnTargetSelected?.Invoke(netEntity);
        }
    }
    public void UpdateState(List<(NetEntity Uid, string Name)> targets)
    {

        TargetsList.Clear(); // Clear list of any existing entities

        foreach (var target in targets)
        {
            var item = new ItemList.Item(TargetsList)
            {
                Text = target.Name,
                Metadata = target.Uid
            };

            TargetsList.Add(item);
        }
    }
}