using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Chat.UI._Paradise;

[GenerateTypedNameReferences]
public sealed partial class TelepathicChatMenu : FancyWindow
{
    public event Action? OnSelectPressed;
    public event Action<NetEntity>? OnTargetSelected;
    public event Action? OnTargetDeselected;

    public TelepathicChatMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SelectButton.OnPressed += _ => OnSelectPressed?.Invoke();
        TargetsList.OnItemSelected += OnItemSelected;
        TargetsList.OnItemDeselected += OnItemDeselected;
    }

    private void OnItemSelected(ItemList.ItemListSelectedEventArgs obj)
    {
        var item = TargetsList[obj.ItemIndex].Metadata;

        if (item is NetEntity netEntity)
        {
            OnTargetSelected?.Invoke(netEntity);
        }
    }

    private void OnItemDeselected(ItemList.ItemListDeselectedEventArgs obj)
    {
        OnTargetDeselected?.Invoke();
    }
    public void BuildList(List<(NetEntity Uid, string Name)> targets)
    {

        TargetsList.Clear(); // Clear list of any existing entities

        foreach (var target in targets)
        {
            var item = new ItemList.Item(TargetsList)
            {
                Text = target.Name,
                Metadata = target.Uid
            };

            TargetsList.Add(item);
        }
    }
}