using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.Stylesheets.Colorspace;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Controls
{
    [GenerateTypedNameReferences]
    [Virtual]
    public partial class SplitBar : BoxContainer
    {

        public const string SplitBarEntry = "SplitBarEntry";

        public Vector2 MinBarSize = new(24, 0);

        public SplitBar()
        {
            RobustXamlLoader.Load(this);
        }

        public void Clear()
        {
            Contents.RemoveAllChildren();
        }

        public void AddEntry(float amount, Color color, string? tooltip = null)
        {
            Contents.AddChild(new PanelContainer
            {
                ToolTip = tooltip,
                HorizontalExpand = true,
                SizeFlagsStretchRatio = amount,
                MouseFilter = MouseFilterMode.Stop,
                StyleClasses = {  SplitBarEntry },
                MinSize = MinBarSize,
                Modulate = color.NudgeChroma(-0.05f),
            });
        }
    }
}
